site_name: 'EKS-A Gloo Edge'
site_url: https://kameshsampath.github.io/gloo-edge-eks-a-demo/
theme:
  name: material
  features:
    - content.code.annotate
    - content.tabs.link
  highlightjs: true
  hljs_languages:
    - yaml
    - yml
    - shell
    - bash
    - javascript
nav:
  - 'Gloo Edge on EKS-A in 5 minutes': "blog.md"
  - 'Tutorial':
    - 'Overview': "tutorial.md"
    - 'Setup': "setup.md"
    - "Gloo Edge with AWS Lambda": "lambda.md"
    - "Gloo Edge with Microservice": "microservice.md"
markdown_extensions:
  - toc:
      baselevel: 1
      permalink: "&para;"
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - smarty
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

